/*
 * JS for BrowsingInterested generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a4cc3150-80d9-438a-9c96-e11154eb1f48';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

// Appery.io push registration service
var _pushRegistrationApperyService = new Apperyio.RestService({
    'url': 'https://api.appery.io/rest/push/reg',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});

Apperyio.AppPages = [{
    "name": "ConfirmInvite",
    "location": "ConfirmInvite.html"
}, {
    "name": "LandingPage",
    "location": "LandingPage.html"
}, {
    "name": "BrowsingInterested",
    "location": "BrowsingInterested.html"
}, {
    "name": "Main",
    "location": "Main.html"
}, {
    "name": "BrowsingCofounders",
    "location": "BrowsingCofounders.html"
}, {
    "name": "UpdateProfile",
    "location": "UpdateProfile.html"
}, {
    "name": "Contact",
    "location": "Contact.html"
}, {
    "name": "Swipe",
    "location": "Swipe.html"
}];

function BrowsingInterested_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_134': 'BrowsingInterested_mobilebutton_134',
        'mobilelabel_135': 'BrowsingInterested_mobilelabel_135',
        'mobilelabel_12': 'BrowsingInterested_mobilelabel_12',
        'mobilelabel_117': 'BrowsingInterested_mobilelabel_117',
        'mobilelabel_118': 'BrowsingInterested_mobilelabel_118',
        'mobilelabel_119': 'BrowsingInterested_mobilelabel_119',
        'mobilelabel_120': 'BrowsingInterested_mobilelabel_120',
        'mobilelabel_121': 'BrowsingInterested_mobilelabel_121',
        'mobilelabel_122': 'BrowsingInterested_mobilelabel_122',
        'mobilegrid_136': 'BrowsingInterested_mobilegrid_136',
        'mobilegridcell_137': 'BrowsingInterested_mobilegridcell_137',
        'mobilebutton_141': 'BrowsingInterested_mobilebutton_141',
        'mobilegridcell_138': 'BrowsingInterested_mobilegridcell_138',
        'button_invite': 'BrowsingInterested_button_invite',
        'mobilegridcell_139': 'BrowsingInterested_mobilegridcell_139',
        'mobilegridcell_140': 'BrowsingInterested_mobilegridcell_140',
        'mobileimage_142': 'BrowsingInterested_mobileimage_142',
        'mobilegrid_31': 'BrowsingInterested_mobilegrid_31',
        'mobilegridcell_32': 'BrowsingInterested_mobilegridcell_32',
        'mobilelabel_36': 'BrowsingInterested_mobilelabel_36',
        'errorHeader_label': 'BrowsingInterested_errorHeader_label',
        'error_label': 'BrowsingInterested_error_label',
        'loginInfo_label': 'BrowsingInterested_loginInfo_label'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["BrowsingInterested_Main_displayUsers_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Main_displayUsers_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['token']"

            }

            ]
        },

        {
            "from_name": "User",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Main_displayUsers_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['client_location']",
                "target": "$['parameters']['client_location']"

            },

            {

                "source": "$['client_ip']",
                "target": "$['parameters']['client_ip']"

            },

            {

                "source": "$['client_device_id']",
                "target": "$['parameters']['client_device_id']"

            },

            {

                "source": "$['latitude']",
                "target": "$['parameters']['latitude']"

            },

            {

                "source": "$['longitude']",
                "target": "$['parameters']['longitude']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["BrowsingInterested_Main_displayUsers_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [

        {
            "from_name": "Main_displayUsers_clone_1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "User_list_arr",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']",
                "target": "$"

            },

            {

                "source": "$['body'][i]['user_id']",
                "target": "$[i]['user_id']"

            },

            {

                "source": "$['body'][i]['user_nickname']",
                "target": "$[i]['user_nickname']"

            },

            {

                "source": "$['body'][i]['user_expertise']",
                "target": "$[i]['user_expertise']"

            },

            {

                "source": "$['body'][i]['user_pitch']",
                "target": "$[i]['user_pitch']"

            },

            {

                "source": "$['body'][i]['user_seeking']",
                "target": "$[i]['user_seeking']"

            },

            {

                "source": "$['body'][i]['user_intro_email']",
                "target": "$[i]['user_intro_email']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["BrowsingInterested_Main_getGeoLocation_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [

        {

            "to_name": "Main_getGeoLocation_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["BrowsingInterested_Main_getGeoLocation_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [

        {
            "from_name": "Main_getGeoLocation_clone_1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "User",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$['latitude']"

            },

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$['longitude']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["BrowsingInterested_Main_getInvitations_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [

        {

            "to_name": "Main_getInvitations_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["BrowsingInterested_Main_getInvitations_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": []
    };

    Apperyio.mappings["BrowsingInterested_Main_display_data_user_clone_1_onbeforesend_mapping_1"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Main_display_data_user_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["BrowsingInterested_Main_display_data_user_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "BrowsingInterested",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.Main_displayUsers_clone_1 = Apperyio.datasources.Main_displayUsers_clone_1 = new Apperyio.DataSource(display_users_list, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_displayUsers_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_displayUsers_clone_1_onsuccess_mapping_0"]);
            try {
                var err = JSON.parse(data).error;
                if (err) {
                    //alert(err);
                    Apperyio("error_label").text(err);
                    Apperyio("error_popup").popup("open");
                    return;
                }
            } catch (ex) {

            }

            try {
                var len = Apperyio.storage.User_list_arr.get().length;
                if (!len) {
                    Apperyio("error_label").text("We are sorry, but there is no one is near you. Try one more time a bit later.");
                    Apperyio("error_popup").popup("open");
                }

                var UserList = Apperyio.storage.User_list_arr.get();
                //var length = UserList.length;
                user_nickname = UserList[0].user_nickname || "Empty";
                user_expertise = UserList[0].user_expertise || "Empty";
                user_pitch = UserList[0].user_pitch || "Empty";
                user_seeking = UserList[0].user_seeking || "Empty";

                Apperyio('label_nickname').text(user_nickname);
                Apperyio('label_expertise').text(user_expertise);
                Apperyio('label_pitch').text(user_pitch);
                Apperyio('label_seeking').text("Seeking: " + user_seeking);

            } catch (ex) {

            }

            if (Apperyio.storage.logged.get()) {
                $('[name=button_invite]').removeClass('ui-dimmed');
                $('[name=invitations_button]').removeClass('ui-dimmed');
                //$('[name=button_edit_prof]').removeClass('ui-disabled');
                $('[name=reg_button]').addClass('ui-disabled');

            } else {
                $('[name=button_invite]').addClass('ui-dimmed');
                $('[name=invitations_button]').addClass('ui-dimmed');
                //$('[name=button_edit_prof]').addClass('ui-disabled');
                $('[name=reg_button]').removeClass('ui-disabled');
            }

            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            console.log("Main:displayUsers=Failed[" + textStatus + "]");
        }
    });

    window.Main_getGeoLocation_clone_1 = Apperyio.datasources.Main_getGeoLocation_clone_1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_getGeoLocation_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_getGeoLocation_clone_1_onsuccess_mapping_0"]);
            try {
                Main_displayUsers_clone_1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio("error_label").text("We couldn't find you location. Please turn your GPS ON.");
            Apperyio("error_popup").popup("open");
            Apperyio("refresh_button").show();
        }
    });

    window.Main_getInvitations_clone_1 = Apperyio.datasources.Main_getInvitations_clone_1 = new Apperyio.DataSource(display_invitations, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_getInvitations_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_getInvitations_clone_1_onsuccess_mapping_0"]);
            if (data.code == "408") {

            } else {

            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            console.log("Main:getInvitationsr=Failed[" + textStatus + "]");
        }
    });

    window.Main_display_data_user_clone_1 = Apperyio.datasources.Main_display_data_user_clone_1 = new Apperyio.DataSource(display_user_data, {
        "onBeforeSend": function(jqXHR) {
            console.log("Main:displayDataUser_Started");
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_display_data_user_clone_1_onbeforesend_mapping_1"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["BrowsingInterested_Main_display_data_user_clone_1_onsuccess_mapping_0"]);
            if (data && !data.code) {
                if (!data.user_area || !data.user_expertise || !data.user_intro_email || !data.user_pitch) {
                    Apperyio.storage.logged.set(false);
                } else {
                    Apperyio.storage.logged.set(true);
                }
            };
            try {
                Main_displayUsers_clone_1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            console.log("Main:displayDataUser=Failed[" + textStatus + "]");
        }
    });

    /*
     * Appery.io Push-notification registration service
     */
    Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"] = {
        "homeScreen": "BrowsingInterested",
        "directions": [{
            "from_name": "pushNotificationToken",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['token']"
            }]
        }, {
            "from_name": "pushNotificationDeviceID",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['deviceID']"
            }]
        }, {
            "from_name": "deviceTimeZone",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['timeZone']"
            }]
        }, {
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "target_transformation": function(value) {
                    return Apperyio.getProjectGUID();
                },
                "target": "$['headers']['X-Appery-App-Id']"
            }, {
                "target_transformation": function(value) {
                    return Apperyio.getTargetPlatform();
                },
                "target": "$['body']['type']"
            }]
        }]
    };

    var _registerPushApperyDS = Apperyio.datasources._registerPushApperyDS = new Apperyio.DataSource(_pushRegistrationApperyService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"]);
        },
        'onComplete': function(jqXHR, textStatus) {},
        'onSuccess': function(data) {
            console.info('App successfully registered with Appery.io Push service');
            $(document).trigger('pushregistrationsuccess');
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            $(document).trigger('pushregistrationfail');
        }
    });

    Apperyio.CurrentScreen = 'BrowsingInterested';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var BrowsingInterested_onLoad = function() {
            BrowsingInterested_elementsExtraJS();

            try {
                Apperyio.storage.User_list_arr.set();
                Apperyio.storage.User_list_id.set(0);

                if (Apperyio.storage.logged.get() === undefined) {
                    Apperyio.storage.logged.set(false);
                }
            } catch (ex) {
                console.log("Main exception=" + ex);
            };
            try {
                Main_display_data_user_clone_1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            BrowsingInterested_deviceEvents();
            BrowsingInterested_windowEvents();
            BrowsingInterested_elementsEvents();
        };

    // screen window events


    function BrowsingInterested_windowEvents() {

        $('#BrowsingInterested').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#BrowsingInterested').on({
            swipeleft: function(event) {
                try {
                    var UserList = Apperyio.storage.User_list_arr.get();
                    var length = UserList.length;
                    var lastIndex = Apperyio.storage.User_list_id.get();
                    var i = lastIndex + 1;
                    if (i >= length) {
                        i = 0;
                    }

                    user_nickname = UserList[i].user_nickname || "Empty";
                    user_expertise = UserList[i].user_expertise || "Empty";
                    user_pitch = UserList[i].user_pitch || "Empty";
                    user_seeking = UserList[i].user_seeking || "Empty";
                    Apperyio('label_nickname').text(user_nickname);
                    Apperyio('label_expertise').text(user_expertise);
                    Apperyio('label_pitch').text(user_pitch);
                    Apperyio('label_seeking').text("Seeking: " + user_seeking);

                    if (UserList[i].user_invitations > 0) {
                        Apperyio('label_click_invitation').show();
                        Apperyio('label_click_invitation').text('Click to see ' + UserList[i].user_invitations + ' invitation pending');
                    } else {
                        Apperyio('label_click_invitation').hide();
                    }

                    Apperyio.storage.User_list_id.set(i);
                } catch (ex) {
                    console.log("Main exception=" + ex);
                };
            },
            swiperight: function(event) {
                try {
                    var UserList = Apperyio.storage.User_list_arr.get();
                    var length = UserList.length;
                    var lastIndex = Apperyio.storage.User_list_id.get();
                    var i = lastIndex - 1;
                    if (lastIndex <= 0) {
                        i = length - 1;
                    }

                    user_nickname = UserList[i].user_nickname || "Empty";
                    user_expertise = UserList[i].user_expertise || "Empty";
                    user_pitch = UserList[i].user_pitch || "Empty";
                    user_seeking = UserList[i].user_seeking || "Empty";
                    Apperyio('label_nickname').text(user_nickname);
                    Apperyio('label_expertise').text(user_expertise);
                    Apperyio('label_pitch').text(user_pitch);
                    Apperyio('label_seeking').text("Seeking: " + user_seeking);

                    if (UserList[i].user_invitations > 0) {
                        Apperyio('label_click_invitation').show();
                        Apperyio('label_click_invitation').text('Click to see ' + UserList[i].user_invitations + ' invitation pending');
                    } else {
                        Apperyio('label_click_invitation').hide();
                    }

                    Apperyio.storage.User_list_id.set(i);
                } catch (ex) {
                    console.log("Main exception=" + ex);
                };
            },
        });

    };

    // device events


    function BrowsingInterested_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("pushinit", function() {
                localStorage.setItem('pushNotificationToken', arguments[1].registrationId);
                _registerPushApperyDS.execute({});
            });

            localStorage.setItem('pushNotificationDeviceID', device.uuid);

            var offset = new Date().getTimezoneOffset();
            var hr = parseInt(offset / (-60));
            var min = -offset - hr * 60;
            var tmin = '' + min;
            var timezone = 'UTC' + (hr > 0 ? '+' + hr : hr) + ':' + (tmin.length > 1 ? tmin : '0' + tmin);
            localStorage.setItem('deviceTimeZone', timezone);

            var push = PushNotification.init({
                ios: {
                    alert: false,
                    badge: false,
                    sound: false
                },
                android: {
                    senderID: ''
                }
            });

            push.on('registration', function(data) {
                $(document).trigger('pushinit', data);
            });

            push.on('notification', function(data) {
                $(document).trigger('push-notification', data);
            });

            push.on('error', function(e) {
                console.log("Error: " + e.message);
            });

        });
    };

    // screen elements extra js


    function BrowsingInterested_elementsExtraJS() {
        // screen (BrowsingInterested) extra code

        /* error_popup */
        $("#BrowsingInterested_error_popup").popup("option", "positionTo", "window");

        /* login_popup */
        $("#BrowsingInterested_login_popup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function BrowsingInterested_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#BrowsingInterested_mobilecontainer [name="button_invite"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    if (Apperyio.storage.logged.get()) {
                        Apperyio.navigateTo("Invitation_Approval");
                    } else {
                        Apperyio("login_popup").popup("open");
                    };

                }
            },
        }, '#BrowsingInterested_mobilecontainer [name="button_invite"]');

        $(document).off("click", '#BrowsingInterested_mobilefooter [name="mobilelabel_36"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('LandingPage', {
                        reverse: false
                    });

                }
            },
        }, '#BrowsingInterested_mobilefooter [name="mobilelabel_36"]');

    };

    $(document).off("pagebeforeshow", "#BrowsingInterested").on("pagebeforeshow", "#BrowsingInterested", function(event, ui) {
        Apperyio.CurrentScreen = "BrowsingInterested";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    BrowsingInterested_onLoad();
};

$(document).off("pagecreate", "#BrowsingInterested").on("pagecreate", "#BrowsingInterested", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BrowsingInterested_js();
});