var sounds=["bubbles",
"clay",
"confetti",
"corona",
"dotted-spiral",
"flash-1",
"flash-2",
"flash-3",
"glimmer",
"moon",
"pinwheel",
"piston-1",
"piston-2",
"piston-3",
"prism-1",
"prism-2",
"prism-3",
"splits",
"squiggle",
"strike",
"suspension",
"timer",
"ufo",
"veil",
"wipe",
"zig-zag"];

var keys = ["q","w","e","r","t","y","u","i","o","p","a","s","d","f","g","h","j","k","l","z","x","c","v","b","n","m"]