/*
 * JS for LandingPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a4cc3150-80d9-438a-9c96-e11154eb1f48';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

// Appery.io push registration service
var _pushRegistrationApperyService = new Apperyio.RestService({
    'url': 'https://api.appery.io/rest/push/reg',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});

Apperyio.AppPages = [{
    "name": "ConfirmInvite",
    "location": "ConfirmInvite.html"
}, {
    "name": "LandingPage",
    "location": "LandingPage.html"
}, {
    "name": "BrowsingInterested",
    "location": "BrowsingInterested.html"
}, {
    "name": "Main",
    "location": "Main.html"
}, {
    "name": "BrowsingCofounders",
    "location": "BrowsingCofounders.html"
}, {
    "name": "UpdateProfile",
    "location": "UpdateProfile.html"
}, {
    "name": "Contact",
    "location": "Contact.html"
}, {
    "name": "Swipe",
    "location": "Swipe.html"
}];

function LandingPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_119': 'LandingPage_mobilebutton_119',
        'mobilelabel_120': 'LandingPage_mobilelabel_120',
        'mobilelabel_10': 'LandingPage_mobilelabel_10',
        'mobilegrid_11': 'LandingPage_mobilegrid_11',
        'mobilegridcell_12': 'LandingPage_mobilegridcell_12',
        'mobileimage_52': 'LandingPage_mobileimage_52',
        'mobilegridcell_44': 'LandingPage_mobilegridcell_44',
        'mobilelabel_53': 'LandingPage_mobilelabel_53',
        'mobilegridcell_38': 'LandingPage_mobilegridcell_38',
        'mobileimage_60': 'LandingPage_mobileimage_60',
        'mobilegridcell_45': 'LandingPage_mobilegridcell_45',
        'mobilelabel_54': 'LandingPage_mobilelabel_54',
        'mobilegridcell_39': 'LandingPage_mobilegridcell_39',
        'mobileimage_61': 'LandingPage_mobileimage_61',
        'mobilegridcell_46': 'LandingPage_mobilegridcell_46',
        'mobilelabel_55': 'LandingPage_mobilelabel_55',
        'mobilegridcell_40': 'LandingPage_mobilegridcell_40',
        'mobileimage_62': 'LandingPage_mobileimage_62',
        'mobilegridcell_47': 'LandingPage_mobilegridcell_47',
        'mobilelabel_56': 'LandingPage_mobilelabel_56',
        'mobilegridcell_41': 'LandingPage_mobilegridcell_41',
        'mobileimage_63': 'LandingPage_mobileimage_63',
        'mobilegridcell_48': 'LandingPage_mobilegridcell_48',
        'mobilelabel_57': 'LandingPage_mobilelabel_57',
        'mobilegridcell_42': 'LandingPage_mobilegridcell_42',
        'mobileimage_64': 'LandingPage_mobileimage_64',
        'mobilegridcell_49': 'LandingPage_mobilegridcell_49',
        'mobilelabel_58': 'LandingPage_mobilelabel_58',
        'mobilegridcell_43': 'LandingPage_mobilegridcell_43',
        'mobileimage_65': 'LandingPage_mobileimage_65',
        'mobilegridcell_50': 'LandingPage_mobilegridcell_50',
        'mobilelabel_59': 'LandingPage_mobilelabel_59',
        'message_grid': 'LandingPage_message_grid',
        'message_cell': 'LandingPage_message_cell',
        'mobilelabel_72': 'LandingPage_mobilelabel_72',
        'mess_textarea': 'LandingPage_mess_textarea',
        'introEmail_input': 'LandingPage_introEmail_input',
        'mobilebutton_121': 'LandingPage_mobilebutton_121',
        'error_label': 'LandingPage_error_label',
        'succ_label': 'LandingPage_succ_label'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["LandingPage_Landing_getUserDetails_onbeforesend_mapping_0"] = {
        "homeScreen": "LandingPage",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Landing_getUserDetails",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['token']"

            }

            ]
        },

        {
            "from_name": "User",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Landing_getUserDetails",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['user_id']",
                "target": "$['parameters']['user_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["LandingPage_Landing_getUserDetails_onsuccess_mapping_0"] = {
        "homeScreen": "LandingPage",
        "directions": [

        {
            "from_name": "Landing_getUserDetails",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "LandingPage",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['user_intro_email']",
                "target": "$['introEmail_input:text']"

            }

            ]
        },

        {
            "from_name": "Landing_getUserDetails",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "User",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['user_intro_email']",
                "target": "$['email']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["LandingPage_Landing_getInfo_onbeforesend_mapping_0"] = {
        "homeScreen": "LandingPage",
        "directions": [

        {
            "from_name": "User",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Landing_getInfo",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['token']",
                "target": "$['parameters']['token']"

            }

            ]
        },

        {
            "from_name": "LandingPage",
            "from_type": "UI",

            "to_name": "Landing_getInfo",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['mess_textarea:text']",
                "target": "$['parameters']['user_landing_page_msg']"

            },

            {

                "source": "$['introEmail_input:text']",
                "target": "$['parameters']['user_landing_page_mail']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["LandingPage_Landing_getInfo_onsuccess_mapping_0"] = {
        "homeScreen": "LandingPage",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.Landing_getUserDetails = Apperyio.datasources.Landing_getUserDetails = new Apperyio.DataSource(display_user_data, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["LandingPage_Landing_getUserDetails_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["LandingPage_Landing_getUserDetails_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Landing_getInfo = Apperyio.datasources.Landing_getInfo = new Apperyio.DataSource(COFound_landingInfo_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["LandingPage_Landing_getInfo_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["LandingPage_Landing_getInfo_onsuccess_mapping_0"]);
            Apperyio("succ_label").text("Message succesfully sent");
            Apperyio("succ_popup").popup("open");
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    /*
     * Appery.io Push-notification registration service
     */
    Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"] = {
        "homeScreen": "LandingPage",
        "directions": [{
            "from_name": "pushNotificationToken",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['token']"
            }]
        }, {
            "from_name": "pushNotificationDeviceID",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['deviceID']"
            }]
        }, {
            "from_name": "deviceTimeZone",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['timeZone']"
            }]
        }, {
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "target_transformation": function(value) {
                    return Apperyio.getProjectGUID();
                },
                "target": "$['headers']['X-Appery-App-Id']"
            }, {
                "target_transformation": function(value) {
                    return Apperyio.getTargetPlatform();
                },
                "target": "$['body']['type']"
            }]
        }]
    };

    var _registerPushApperyDS = Apperyio.datasources._registerPushApperyDS = new Apperyio.DataSource(_pushRegistrationApperyService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"]);
        },
        'onComplete': function(jqXHR, textStatus) {},
        'onSuccess': function(data) {
            console.info('App successfully registered with Appery.io Push service');
            $(document).trigger('pushregistrationsuccess');
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            $(document).trigger('pushregistrationfail');
        }
    });

    Apperyio.CurrentScreen = 'LandingPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var LandingPage_onLoad = function() {
            LandingPage_elementsExtraJS();

            var user = Apperyio.storage.User.get();
            if (user && user.email) {
                Apperyio("introEmail_input").val(user.email);
            } else {
                Landing_getUserDetails.execute();
            };

            LandingPage_deviceEvents();
            LandingPage_windowEvents();
            LandingPage_elementsEvents();
        };

    // screen window events


    function LandingPage_windowEvents() {

        $('#LandingPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function LandingPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("pushinit", function() {
                localStorage.setItem('pushNotificationToken', arguments[1].registrationId);
                _registerPushApperyDS.execute({});
            });

            localStorage.setItem('pushNotificationDeviceID', device.uuid);

            var offset = new Date().getTimezoneOffset();
            var hr = parseInt(offset / (-60));
            var min = -offset - hr * 60;
            var tmin = '' + min;
            var timezone = 'UTC' + (hr > 0 ? '+' + hr : hr) + ':' + (tmin.length > 1 ? tmin : '0' + tmin);
            localStorage.setItem('deviceTimeZone', timezone);

            var push = PushNotification.init({
                ios: {
                    alert: false,
                    badge: false,
                    sound: false
                },
                android: {
                    senderID: ''
                }
            });

            push.on('registration', function(data) {
                $(document).trigger('pushinit', data);
            });

            push.on('notification', function(data) {
                $(document).trigger('push-notification', data);
            });

            push.on('error', function(e) {
                console.log("Error: " + e.message);
            });

        });
    };

    // screen elements extra js


    function LandingPage_elementsExtraJS() {
        // screen (LandingPage) extra code

        /* error_popup */
        $("#LandingPage_error_popup").popup("option", "positionTo", "window");

        /* succ_popup */
        $("#LandingPage_succ_popup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function LandingPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#LandingPage").on("pagebeforeshow", "#LandingPage", function(event, ui) {
        Apperyio.CurrentScreen = "LandingPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    LandingPage_onLoad();
};

$(document).off("pagecreate", "#LandingPage").on("pagecreate", "#LandingPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    LandingPage_js();
});