/*
 * JS for Main generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a4cc3150-80d9-438a-9c96-e11154eb1f48';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

// Appery.io push registration service
var _pushRegistrationApperyService = new Apperyio.RestService({
    'url': 'https://api.appery.io/rest/push/reg',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});

Apperyio.AppPages = [{
    "name": "ConfirmInvite",
    "location": "ConfirmInvite.html"
}, {
    "name": "LandingPage",
    "location": "LandingPage.html"
}, {
    "name": "BrowsingInterested",
    "location": "BrowsingInterested.html"
}, {
    "name": "Main",
    "location": "Main.html"
}, {
    "name": "BrowsingCofounders",
    "location": "BrowsingCofounders.html"
}, {
    "name": "UpdateProfile",
    "location": "UpdateProfile.html"
}, {
    "name": "Contact",
    "location": "Contact.html"
}, {
    "name": "Swipe",
    "location": "Swipe.html"
}];

function Main_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'CFWMLogo_image': 'Main_CFWMLogo_image',
        'mobilelabel_45': 'Main_mobilelabel_45',
        'mobilebutton_41': 'Main_mobilebutton_41',
        'mobilebutton_42': 'Main_mobilebutton_42',
        'mobilebutton_43': 'Main_mobilebutton_43',
        'mobileimage_46': 'Main_mobileimage_46',
        'mobilelabel_10': 'Main_mobilelabel_10',
        'email_label': 'Main_email_label',
        'action_grid': 'Main_action_grid',
        'mobilegridcell_13': 'Main_mobilegridcell_13',
        'LNForm_button': 'Main_LNForm_button',
        'mobilegridcell_14': 'Main_mobilegridcell_14',
        'proceedLogin_button': 'Main_proceedLogin_button',
        'errorHeader_label': 'Main_errorHeader_label',
        'errorValue_label': 'Main_errorValue_label',
        'welcom_label': 'Main_welcom_label'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Main_Login_confUserLogin_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "User",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Login_confUserLogin",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['email']",
                "target": "$['parameters']['user_email']"

            },

            {

                "source": "$['password']",
                "target": "$['parameters']['user_password']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_Login_confUserLogin_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": []
    };

    Apperyio.mappings["Main_Login_deviceLogin_onbeforesend_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {

            "to_name": "Login_deviceLogin",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Content-Type": "application/json"
                },
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "target_transformation": function(value) {
                    return localStorage.getItem('pushNotificationDeviceID');
                },
                "target": "$['parameters']['user_device_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Main_Login_deviceLogin_onsuccess_mapping_0"] = {
        "homeScreen": "Main",
        "directions": [

        {
            "from_name": "Login_deviceLogin",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "token",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['Token']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.Login_confUserLogin = Apperyio.datasources.Login_confUserLogin = new Apperyio.DataSource(social_user_login, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Login_confUserLogin_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Login_confUserLogin_onsuccess_mapping_0"]);
            if (data.Token) {
                Apperyio.storage.User.update("$['token']", data.Token);
                Apperyio.storage.token.set(data.Token);
                Apperyio.navigateTo("Main");
            } else {
                //CoFoundHelper.initSocialGap();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Login_deviceLogin = Apperyio.datasources.Login_deviceLogin = new Apperyio.DataSource(cofwm_device_user_login, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Login_deviceLogin_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Main_Login_deviceLogin_onsuccess_mapping_0"]);
            Apperyio.navigateTo('BrowsingCofounders', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    /*
     * Appery.io Push-notification registration service
     */
    Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"] = {
        "homeScreen": "Main",
        "directions": [{
            "from_name": "pushNotificationToken",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['token']"
            }]
        }, {
            "from_name": "pushNotificationDeviceID",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['deviceID']"
            }]
        }, {
            "from_name": "deviceTimeZone",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['timeZone']"
            }]
        }, {
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "target_transformation": function(value) {
                    return Apperyio.getProjectGUID();
                },
                "target": "$['headers']['X-Appery-App-Id']"
            }, {
                "target_transformation": function(value) {
                    return Apperyio.getTargetPlatform();
                },
                "target": "$['body']['type']"
            }]
        }]
    };

    var _registerPushApperyDS = Apperyio.datasources._registerPushApperyDS = new Apperyio.DataSource(_pushRegistrationApperyService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"]);
        },
        'onComplete': function(jqXHR, textStatus) {},
        'onSuccess': function(data) {
            console.info('App successfully registered with Appery.io Push service');
            $(document).trigger('pushregistrationsuccess');
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            $(document).trigger('pushregistrationfail');
        }
    });

    Apperyio.CurrentScreen = 'Main';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Main_onLoad = function() {
            Main_elementsExtraJS();

            Main_deviceEvents();
            Main_windowEvents();
            Main_elementsEvents();
        };

    // screen window events


    function Main_windowEvents() {

        $('#Main').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Main_deviceEvents() {
        document.addEventListener("deviceready", function() {
            Apperyio("login2_popup").popup("open");
            setTimeout(function() {
                try {

                    console.log(localStorage.getItem('pushNotificationDeviceID'));
                    if (Apperyio.storage.User.get()) {
                        var utoken = Apperyio.storage.User.get().token;
                        if (utoken) {
                            Apperyio.storage.User.update("$['token']", "");
                        }
                    }

                    var token = Apperyio.storage.token.get();
                    if (token) {
                        Apperyio.storage.token.set("");
                    }

                    var user = Apperyio.storage.User.get();

                    if (user && user.cfwm_id) {
                        // make login and obtain token for future api calls
                        //setTimeout(function(){
                        //Apperyio("email_label").text(user.email);
                        //Apperyio("login_popup").popup("open");
                        //}, 1000);
                        if (localStorage.getItem('pushNotificationDeviceID') !== user.cfwm_id) {
                            Apperyio.storage.User.update('$["cfwm_id"]', localStorage.getItem('pushNotificationDeviceID'));

                        }
                    } else {
                        if (localStorage.getItem('pushNotificationDeviceID')) {
                            Apperyio.storage.User.update("$['cfwm_id']", localStorage.getItem('pushNotificationDeviceID'));
                        }
                    }

                    Login_deviceLogin.execute();
                } catch (ex) {
                    console.log("Login:DeviceReady = Failed[" + ex + "]");
                }
            }, 1000);

            $(document).bind("pushinit", function() {
                localStorage.setItem('pushNotificationToken', arguments[1].registrationId);
                _registerPushApperyDS.execute({});
            });

            localStorage.setItem('pushNotificationDeviceID', device.uuid);

            var offset = new Date().getTimezoneOffset();
            var hr = parseInt(offset / (-60));
            var min = -offset - hr * 60;
            var tmin = '' + min;
            var timezone = 'UTC' + (hr > 0 ? '+' + hr : hr) + ':' + (tmin.length > 1 ? tmin : '0' + tmin);
            localStorage.setItem('deviceTimeZone', timezone);

            var push = PushNotification.init({
                ios: {
                    alert: false,
                    badge: false,
                    sound: false
                },
                android: {
                    senderID: ''
                }
            });

            push.on('registration', function(data) {
                $(document).trigger('pushinit', data);
            });

            push.on('notification', function(data) {
                $(document).trigger('push-notification', data);
            });

            push.on('error', function(e) {
                console.log("Error: " + e.message);
            });

        });
    };

    // screen elements extra js


    function Main_elementsExtraJS() {
        // screen (Main) extra code

        /* login_popup */
        $("#Main_login_popup").popup("option", "positionTo", "window");

        /* error_popup */
        $("#Main_error_popup").popup("option", "positionTo", "window");

        /* login2_popup */
        $("#Main_login2_popup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function Main_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Main").on("pagebeforeshow", "#Main", function(event, ui) {
        Apperyio.CurrentScreen = "Main";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Main_onLoad();
};

$(document).off("pagecreate", "#Main").on("pagecreate", "#Main", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Main_js();
});