/*
 * JS for ConfirmInvite generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a4cc3150-80d9-438a-9c96-e11154eb1f48';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

// Appery.io push registration service
var _pushRegistrationApperyService = new Apperyio.RestService({
    'url': 'https://api.appery.io/rest/push/reg',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});

Apperyio.AppPages = [{
    "name": "ConfirmInvite",
    "location": "ConfirmInvite.html"
}, {
    "name": "LandingPage",
    "location": "LandingPage.html"
}, {
    "name": "BrowsingInterested",
    "location": "BrowsingInterested.html"
}, {
    "name": "Main",
    "location": "Main.html"
}, {
    "name": "BrowsingCofounders",
    "location": "BrowsingCofounders.html"
}, {
    "name": "UpdateProfile",
    "location": "UpdateProfile.html"
}, {
    "name": "Contact",
    "location": "Contact.html"
}, {
    "name": "Swipe",
    "location": "Swipe.html"
}];

function ConfirmInvite_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_119': 'ConfirmInvite_mobilebutton_119',
        'mobilelabel_120': 'ConfirmInvite_mobilelabel_120',
        'mobilelabel_10': 'ConfirmInvite_mobilelabel_10',
        'mobilelabel_122': 'ConfirmInvite_mobilelabel_122',
        'mobilelabel_123': 'ConfirmInvite_mobilelabel_123',
        'mobilelabel_124': 'ConfirmInvite_mobilelabel_124',
        'mobilebutton_121': 'ConfirmInvite_mobilebutton_121',
        'error_label': 'ConfirmInvite_error_label',
        'succ_label': 'ConfirmInvite_succ_label'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["ConfirmInvite_Landing_getUserDetails_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "ConfirmInvite",
        "directions": [

        {
            "from_name": "token",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Landing_getUserDetails_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['token']"

            }

            ]
        },

        {
            "from_name": "User",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Landing_getUserDetails_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['user_id']",
                "target": "$['parameters']['user_id']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["ConfirmInvite_Landing_getUserDetails_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "ConfirmInvite",
        "directions": [

        {
            "from_name": "Landing_getUserDetails_clone_1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "User",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['user_intro_email']",
                "target": "$['email']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["ConfirmInvite_Landing_getInfo_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "ConfirmInvite",
        "directions": [

        {
            "from_name": "User",
            "from_type": "LOCAL_STORAGE",

            "to_name": "Landing_getInfo_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['token']",
                "target": "$['parameters']['token']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["ConfirmInvite_Landing_getInfo_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "ConfirmInvite",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.Landing_getUserDetails_clone_1 = Apperyio.datasources.Landing_getUserDetails_clone_1 = new Apperyio.DataSource(display_user_data, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ConfirmInvite_Landing_getUserDetails_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ConfirmInvite_Landing_getUserDetails_clone_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Landing_getInfo_clone_1 = Apperyio.datasources.Landing_getInfo_clone_1 = new Apperyio.DataSource(COFound_landingInfo_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ConfirmInvite_Landing_getInfo_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ConfirmInvite_Landing_getInfo_clone_1_onsuccess_mapping_0"]);
            Apperyio("succ_label").text("Message succesfully sent");
            Apperyio("succ_popup").popup("open");
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    /*
     * Appery.io Push-notification registration service
     */
    Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"] = {
        "homeScreen": "ConfirmInvite",
        "directions": [{
            "from_name": "pushNotificationToken",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['token']"
            }]
        }, {
            "from_name": "pushNotificationDeviceID",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['deviceID']"
            }]
        }, {
            "from_name": "deviceTimeZone",
            "from_type": "LOCAL_STORAGE",
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "source": "$",
                "target": "$['body']['timeZone']"
            }]
        }, {
            "to_name": "_registerPushApperyDS",
            "to_type": "SERVICE_REQUEST",
            "mappings": [{
                "target_transformation": function(value) {
                    return Apperyio.getProjectGUID();
                },
                "target": "$['headers']['X-Appery-App-Id']"
            }, {
                "target_transformation": function(value) {
                    return Apperyio.getTargetPlatform();
                },
                "target": "$['body']['type']"
            }]
        }]
    };

    var _registerPushApperyDS = Apperyio.datasources._registerPushApperyDS = new Apperyio.DataSource(_pushRegistrationApperyService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"]);
        },
        'onComplete': function(jqXHR, textStatus) {},
        'onSuccess': function(data) {
            console.info('App successfully registered with Appery.io Push service');
            $(document).trigger('pushregistrationsuccess');
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            $(document).trigger('pushregistrationfail');
        }
    });

    Apperyio.CurrentScreen = 'ConfirmInvite';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ConfirmInvite_onLoad = function() {
            ConfirmInvite_elementsExtraJS();

            ConfirmInvite_deviceEvents();
            ConfirmInvite_windowEvents();
            ConfirmInvite_elementsEvents();
        };

    // screen window events


    function ConfirmInvite_windowEvents() {

        $('#ConfirmInvite').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ConfirmInvite_deviceEvents() {
        document.addEventListener("deviceready", function() {

            $(document).bind("pushinit", function() {
                localStorage.setItem('pushNotificationToken', arguments[1].registrationId);
                _registerPushApperyDS.execute({});
            });

            localStorage.setItem('pushNotificationDeviceID', device.uuid);

            var offset = new Date().getTimezoneOffset();
            var hr = parseInt(offset / (-60));
            var min = -offset - hr * 60;
            var tmin = '' + min;
            var timezone = 'UTC' + (hr > 0 ? '+' + hr : hr) + ':' + (tmin.length > 1 ? tmin : '0' + tmin);
            localStorage.setItem('deviceTimeZone', timezone);

            var push = PushNotification.init({
                ios: {
                    alert: false,
                    badge: false,
                    sound: false
                },
                android: {
                    senderID: ''
                }
            });

            push.on('registration', function(data) {
                $(document).trigger('pushinit', data);
            });

            push.on('notification', function(data) {
                $(document).trigger('push-notification', data);
            });

            push.on('error', function(e) {
                console.log("Error: " + e.message);
            });

        });
    };

    // screen elements extra js


    function ConfirmInvite_elementsExtraJS() {
        // screen (ConfirmInvite) extra code

        /* error_popup */
        $("#ConfirmInvite_error_popup").popup("option", "positionTo", "window");

        /* succ_popup */
        $("#ConfirmInvite_succ_popup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function ConfirmInvite_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#ConfirmInvite").on("pagebeforeshow", "#ConfirmInvite", function(event, ui) {
        Apperyio.CurrentScreen = "ConfirmInvite";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ConfirmInvite_onLoad();
};

$(document).off("pagecreate", "#ConfirmInvite").on("pagecreate", "#ConfirmInvite", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ConfirmInvite_js();
});